### PR TITLE
fix: add proper accordion implementation

### LINKED ISSUE #64: Fix supervisor accordion implementation
Currently each suggested supervisor in the recomendation is a separate instance of an accordion with a singular item inside of it. The recommendation should have just one accordion with all of the suggested supervisors being its items

### PR DESCRIPTION
**Pull request by maciejkrol18**
### Changes
- Removed `message-primary` color variable and replaced it with `chat-bot`, as it was the first color used for model responses which provides high level of contrast, and yet it was swapped for very bright blue in later designs for some reason. It's also a common convention in conversation UIs that the user's messages are brighter than the messages of other participants.
- Reworked the accordion:
   - The main `<Accordion/>` element is now located in the `Recommendation` component
   - We map over the supervisors inside of it returning `Supervisor` components
   - The `Supervisor` component now returns `<AccordionItem/>` element
   - Highlighting the currently open accordion is now handled through group/peer tailwind classes and html data attributes instead of state. Radix UI components often expose their state with data attributes which we can then use to conditionally style elements. 

### Mistakes in previous implementation
- Using state the way it was implemented before wouldn't work properly in a properly implemented `<Accordion/>` of type `single`, as the `open` state was triggered by clicking on the `<AccordionTrigger/>`. If we were to click on item A, it would get highlighted, but then if we were to click on item B, item A would still be highlighted along with item B despite it collapsing.
- The `<AccordionItem/>` element in `Supervisor` component had a hard-coded value of `"id"`. Each `<AccordionItem/>` in an `<Accordion/>` should have a unique value, as this is how the radix ui accordion figures out which accordion should be expanded/collapse. Making it a hard-coded, identical value across all accordion item causes all items to expand and collapse at once, no matter which one we click.

### CODE REVIEW

File: src/components/supervisor.tsx [hunk 1]
```diff
@@ -59,36 +55,22 @@ export function Supervisor({
...
-          <AccordionTrigger
-            className="py-0"
-            onClick={() => {
-              setOpen(!open);
-            }}
-          >
-            <div className="flex flex-col gap-1">
-              <p className="text-xl font-bold">{name}</p>
-              <p>{faculties[faculty] || "Nieznany wydział"}</p>
+      <div className="w-full rounded-2xl border border-chat-bot p-4 transition group-data-[state=open]:bg-chat-bot">
```
Comment (chewmanji) [inline src/components/supervisor.tsx:58]: It's cool, didn't know that

**Review by chewmanji — APPROVED** [review]
lgtm

**Review by mejsiejdev — APPROVED** [review]
Nothing to add here - I really like how after the proper implementation we can use the component's `group-data-[state]`
