### PR TITLE
Fix local storage undefined bug

### LINKED ISSUE #32: Fix "localstorage undefined" bug
- add hook which will handle using localstorage to prevent error when using localstorage happens on server side

### PR DESCRIPTION
**Pull request by chewmanji**
- I think there's a better way to handle our case (local storage state and state in components)
- useLocalStorage hook is complicated but it handles state management well
- useChats acts as repository for chats
- maybe using global state would be better solution

### IMPORTANTE
EDIT: after adding jotai
- `useLocalStorage()` hook was removed and Jotai's `useAtom()` is used instead (it is used in `useChats()`)
- `useChats()` hook is now an API for interacting with chats
- in `Sidebar` and `PromptInput` components are snippets of code that use this hook

### CODE REVIEW

File: src/app/chat/[uuid]/page.tsx [hunk 1]
```diff
@@ -1,23 +1,28 @@
...
-    localStorage.getItem("chats") == null
-      ? []
-      : (JSON.parse(localStorage.getItem("chats")!) as Chat[]);
+  useEffect(() => {
+    const foundChat = getChat(parameters.uuid);
+    setChat(foundChat);
 
-  // Find chat by uuid
-  const chat = chats.find((c) => c.uuid === parameters.uuid);
+    //TODO call api there
```
Comment (maciejkrol18) [inline src/app/chat/[uuid]/page.tsx]: **suggestion**: With the current setup, if we implement api logic where that comment is, we will call the api on every chat page load, even if the chat already has a response from the model. We should check whether a response from the model is already saved within the chat object before calling the api. This whole section will be probably refactored as you resolve #31, but I wanted to point this out

Example:
```tsx
  useEffect(() => {
    const foundChat = getChat(parameters.uuid);
    setChat(foundChat);

    // or whatever condition that will signify that we already have a response
    if (!foundChat.recommendation) {
      // api logic here
    }
  }, [parameters.uuid, getChat]);
```

File: src/app/chat/[uuid]/page.tsx [hunk 2]
```diff
@@ -1,23 +1,28 @@
...
+  const { getChat } = useChats();
+  const [chat, setChat] = useState<Chat | null | undefined>(null);
 
-  // Get chats from local storage
-  const chats =
-    localStorage.getItem("chats") == null
-      ? []
-      : (JSON.parse(localStorage.getItem("chats")!) as Chat[]);
+  useEffect(() => {
+    const foundChat = getChat(parameters.uuid);
```
Comment (maciejkrol18) [inline src/app/chat/[uuid]/page.tsx]: **suggestion**: I think calling it "targetChat" or something like that would be better, since `getChat()` returns a local storage response. If a chat with that uuid *is found* within local storage then we get the chat object, but of course a chat with that uuid may not exist, returning *null* in that case - therefore that chat *will not* be always found

File: src/app/chat/[uuid]/page.tsx [hunk 3]
```diff
@@ -1,23 +1,28 @@
...
 
-  // If chat not found, return 404
-  if (!chat) {
+  if (chat === null) {
+    return;
+  }
+
+  if (chat === undefined) {
     notFound();
   }
```
Comment (maciejkrol18) [inline src/app/chat/[uuid]/page.tsx]: **issue:** This whole section needs to be refactored.

Code within `if (chat === undefined)` will *never* be called. Local storage response is either the saved value or null, if no value tied to the given key is found. There's no way for this condition to be met as of now. You can check it by going to `localhost:3000/chat/absolutely-anything-here` to see that no 404 page is shown as the `if (chat === null)` block is called, and that one just returns - resulting in us seeing just a blank page

Our chat page can be in three states
1. Awaiting model response (chat found && no model response already)
2. Showing the suggestions (chat found && model response exists)
3. Showing the 404 page (chat not found)

My suggestion is to remove the two marked `if` blocks and approach this differently: 
Redirect to 404 in the useEffect itself. If `targetChat` is `null` then that means a chat with that uuid *was not* found within the local storage
```tsx
useEffect(() => {
  const targetChat = getChat(parameters.uuid);
  if (targetChat === null) { notFound() }
  setChat(targetChat);
  // ...rest of the code
```
since `null` is the initial value of `chat` state, use it to determine whether we're loading the chat 
```tsx
return <div>{chat ? chat.prompt : "Loading"}</div>;
```

**Review by maciejkrol18 — CHANGES_REQUESTED** [review]
**note:** I honestly haven't played with custom hooks that much but `/hooks/use-chats.tsx` and `/hooks/use-local-storage.tsx` look fine

File: src/app/chat/[uuid]/page.tsx (hunk 1 above)
Comment (chewmanji) [reply src/app/chat/[uuid]/page.tsx]: yup, you're absolutely right

File: src/app/chat/[uuid]/page.tsx (hunk 3 above)
Comment (chewmanji) [reply src/app/chat/[uuid]/page.tsx]: yeah, I messed up it completely (the undefined check is leftover from one of previous implementations)

**Review by maciejkrol18 — APPROVED** [review]

**Comment by chewmanji** [comment]
While experimenting with the hooks it looks that they don't really solve the problem (e.g when adding new chat the state in sidebar won't update unless the user refershe the site - we'd have to do props drilling all the way from layout 👀, which I don't even think is possible 😆)

**Comment by maciejkrol18** [comment]
> While experimenting with the hooks it looks that they don't really solve the problem (e.g when adding new chat the state in sidebar won't update unless the user refershe the site - we'd have to do props drilling all the way from layout 👀, which I don't even think is possible 😆)

That's true, I missed that in my review. Given this fact, I guess you could try to fix it with our current setup (custom hooks), or we could also switch to a global state solution, as you mentioned in your first comment in this PR. We could use **Jotai**, which is mentioned [in solvro docs](https://docs.solvro.pl/guides/web-development/best-practices/#zarz%C4%85dzanie-stanem)

File: src/app/chat/[uuid]/page.tsx [hunk 4]
```diff
@@ -1,25 +1,27 @@
...
+      notFound();
+    }
+    setChat(targetChat);
 
-  // Find chat by uuid
-  const chat = chats.find((c) => c.uuid === parameters.uuid);
+    if (!targetChat.recommendation) {
+      //TODO call api there
+    }
+  }, [parameters.uuid, getChat]);
```
Comment (Rei-x) [inline src/app/chat/[uuid]/page.tsx]: **suggestion**: can we do something like this? I think it would be simpler to not introduce another state

```tsx
export default function ConversationPage() {
  const parameters = useParams<{ uuid: string }>();
  const { getChat, updateChat } = useChats();
  const chat = getChat(parameters.id);
  
  if (chat === null) {
    notFound();
  }
```

**Review by Rei-x — COMMENTED** [review]
those hooks are valid, but as the-king said, you can use Jotai for that, it even has 1party integration with local storage, so you can use it just like useState

https://jotai.org/docs/utilities/storage

```tsx
import { useAtom } from 'jotai'
import { atomWithStorage } from 'jotai/utils'

// persisted to localStorage
const chatsAtom = atomWithStorage<Chat[]>('chats', [])

const Page = () => {
  const [chats, setChats] = useAtom(chatsAtom)

  return (
    <>
      chats go here
    </>
  )
}
```

File: src/app/chat/[uuid]/page.tsx (hunk 4 above)
Comment (chewmanji) [reply src/app/chat/[uuid]/page.tsx]: After migrating to Jotai we can do this I think.

Additional state and `useEffect()` were to address strange behaviour which I don't really understand:
In short, after user refreshes the page (while being on /chat/{uuid}) the 404 is thrown in console, blank screen is displayed for a moment and then actual chat is displayed

Comment (maciejkrol18) [reply src/app/chat/[uuid]/page.tsx]: Probably because chat's page.tsx is a client component, and even those get rendered once on the server. Window API, from which local storage is from does not exist on the server. Server tries to run code which tries to access the local storage and fails - then the client takes over (hydration), local storage code re-runs because of a re-render and then it works

https://docs.solvro.pl/guides/web-development/common-mistakes/#jak-dzia%C5%82aj%C4%85client-components

therefore I think the above suggested approach wouldn't work

File: src/app/chat/layout.tsx [hunk 5]
```diff
@@ -8,8 +9,12 @@ export default function ChatLayout({
     <SidebarProvider>
       <ChatSidebar />
       <div className="flex h-screen w-full flex-col bg-chat-background text-white">
-        <SidebarTrigger className="border-0" />
-        {children}
+        <ClientOnly>
```
Comment (chewmanji) [inline src/app/chat/layout.tsx:12]: Reason for this
https://jotai.org/docs/utilities/storage#server-side-rendering

**Review by maciejkrol18 — APPROVED** [review]
Good job, everything works on my end. I never used Jotai for any of my projects, but I just read the documentation relevant to the code here and everything looks fine
