### PR TITLE
Add bug report form

### LINKED ISSUE #86: Add bug report form
There are rumors that using Google forms as bug report/feedback forms kinda sucks so we'll implement custom form (for now just bug report).

Fields in the form:
- email
- brief description of issue
- steps to reproduce the issue (optional)
- screenshot of issue (optional)

For now, [Web3Forms'](https://web3forms.com/) free plan looks good for our needs
[Web3Forms docs](https://docs.web3forms.com/)

EDIT:
Free plan doesn't include file attachments 😭

EDIT 2:
Use Kamil's idea to integrate with google forms

### PR DESCRIPTION
**Pull request by chewmanji**
Resolves #86 

Used Kamil's idea with google forms integration.
Added bug report option to chat sidebar and in footer in home page.

I've tried to add additional field in form - screenshots - but uploading files in the form requires user to be logged in google account which complicates the problem hard enough so that I couldn't figure out how to handle this.

How it looks:

image
image
image
image

### CODE REVIEW

File: src/types/schemas.ts
Comment (maciejkrol18) [inline src/types/schemas.ts:1]: **note:** I guess we could also bring the schema from `PromptForm` here but I'm not sure whether this is necessary as there's only two properties in it

File: src/actions/bug-report.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    if (!response.ok) {
+      const error = {
+        message: `Bug report submission failed`,
+      };
+      console.error(error.message, response);
+      return { success: false, error };
+    }
+  } catch (error) {
+    console.error("Bug report submission failed:", error);
+  }
```
Comment (maciejkrol18) [inline src/actions/bug-report.ts]: **issue:** I tested the form without setting any env variables. Without the google form url in place, `fetch` throws the following error:
```
Bug report submission failed: TypeError: Failed to parse URL from 
    at async sendBugReportForm (\web-promochator\src\actions\bug-report.ts:24:21)
```
Despite this error being thrown, the UI shows the success screen ("Dziękujemy za zgłoszenie"). We should add returning the `{ success: false, error }` object in the catch block too so any errors within the try-catch block get reported by the UI too
```suggestion
  } catch (error) {
    console.error("Bug report submission failed:", error);
    return { success: false, error };
  }
```

**Review by maciejkrol18 — COMMENTED** [review]
I'm not sure how to go about the images either. A wild workaround that came to my mind is to add a file upload input and when the form gets submitted that image gets converted into base64 and that string gets sent to a hidden field in the google form - we can then decode the image

**Comment by chewmanji** [comment]
Sheeeeesh, it's WILD but we may try it (in a seperate issue 😂)

File: src/types/schemas.ts
Comment (chewmanji) [reply src/types/schemas.ts:1]: For consistency I'll move it
