### PR TITLE
fix: disable scroll when sidebar is open

### LINKED ISSUE #77: Scrolling is not disabled when sidebar is open
User should not be able to scroll when the sidebar is open
Image

### PR DESCRIPTION
**Pull request by mejsiejdev**

### CODE REVIEW

File: src/app/layout.tsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ export default function RootLayout({
 }>) {
   return (
     <html lang="pl" className={poppins.className}>
-      <body>
+      <body className="h-full">
```
Comment (maciejkrol18) [inline src/app/layout.tsx]:
```suggestion
      <body className="min-h-screen">
```

**Review by maciejkrol18 — APPROVED** [review]
